batch_size: 32
beta_beta: 1.0
checkpointing: false
decoder_MADE_gating: true
decoder_MADE_gating_mechanism: 0
decoder_MADE_hidden_sizes: 200-220
decoder_network_type: basic_deconv_decoder
encoder_MADE_hidden_sizes: 200-220
encoder_network_type: basic_conv_encoder
eval_ll_every_n_epochs: 1

