objective : VAE
beta_beta : 1.0
free_bits : 5.0
mdr_value : 8.0
mdr_constraint_optim_lr : 0.001
info_alpha : 0.0
info_lambda : 1000.0
batch_size : 64
max_steps : 1000000
max_epochs : 120
eval_ll_every_n_epochs : 1
gen_opt : adam
gen_lr : 0.0001
gen_l2_weight : 0.0001
gen_momentum : 0.0
inf_opt : adam
inf_lr : 0.0001
inf_l2_weight : 0.0001
inf_momentum : 0.0
max_gradient_norm : 1.0
iw_n_samples : 50
latent_dim : 10
decoder_network_type : basic_deconv_decoder
decoder_MADE_gating : True
encoder_network_type : basic_conv_encoder
q_z_x_type : conditional_gaussian_made
p_z_type : isotropic_gaussian
mog_n_components : 5
p_x_z_type : bernoulli
image_or_language : image
data_distribution : bernoulli
image_dataset_name : bmnist
image_w_h : 28
n_channels : 1
tokenizer_name : roberta
language_dataset_name : ptb_text_only
vocab_size : 50265
num_workers : 6
max_seq_len : 64
print_stats : True
print_every_n_steps : 50
logging : True
checkpointing : True
log_every_n_steps : 5
wandb_project : fall-2021-VAE
gpus : 1
ddp : False
short_dev_run : False
run_name_prefix : (27 sept)