batch_size: 64
checkpointing: false
data_distribution: bernoulli
decoder_MADE_gating: true
decoder_MADE_gating_mechanism: 1
decoder_MADE_hidden_sizes: 8000-8000
decoder_network_type: conditional_made_decoder
encoder_MADE_hidden_sizes: 500-500
encoder_network_type: basic_conv_encoder
eval_ll_every_n_epochs: 1
iw_n_samples: 50
latent_dim: 64
log_every_n_steps: 1
logging: false
max_epochs: 120
max_gradient_norm: 1.0
max_steps: 1000000
mog_n_components: 3
n_channels: 1
num_workers: 3
objective: VAE
p_x_z_type: bernoulli
p_z_type: mog
print_every_n_steps: 1
print_stats: true
q_z_x_type: independent_gaussian
run_name_prefix: ''
short_dev_run: True
wandb_project: fall-2021-VAE
